[package]
name = "spl-token-client"
version = "0.16.1"
description = "SPL-Token Rust Client"
documentation = "https://docs.rs/spl-token-client"
readme = "README.md"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = ["display"]
display = ["dep:solana-cli-output"]

[dependencies]
async-trait = "0.1"
bincode = "1.3.2"
bytemuck = "1.23.1"
futures = "0.3.31"
futures-util = "0.3"
solana-banks-interface = "2.3.4"
solana-cli-output = { version = "2.2.0", optional = true }
solana-program-test = "2.3.4"
solana-rpc-client = "2.3.4"
solana-rpc-client-api = "2.3.4"
solana-sdk = "2.2.1"
solana-system-interface = "1"
spl-associated-token-account-client = { version = "2.0.0" }
spl-elgamal-registry = { version = "0.3.0",features = ["no-entrypoint"], path = "../../confidential-transfer/elgamal-registry"}
spl-memo = { version = "6.0", features = ["no-entrypoint"] }
spl-record = { version = "0.3.0", features = ["no-entrypoint"] }
spl-token = { version = "8.0", features = ["no-entrypoint"] }
spl-token-confidential-transfer-proof-extraction = { version = "0.4.0", path = "../../confidential-transfer/proof-extraction" }
spl-token-confidential-transfer-proof-generation = { version = "0.4.0", path = "../../confidential-transfer/proof-generation" }
spl-token-2022 = { version = "9.0.0", features = ["no-entrypoint"], path = "../../program" }
spl-token-group-interface = { version = "0.6.0" }
spl-token-metadata-interface = { version = "0.7.0" }
spl-transfer-hook-interface = { version = "0.10.0" }
thiserror = "2.0"

[dev-dependencies]
async-trait = "0.1"
borsh = "1.5.7"
bytemuck = "1.23.1"
futures-util = "0.3"
solana-program = "2.3.0"
spl-associated-token-account = { version = "7.0.0" }
spl-pod = { version = "0.5.1" }
spl-instruction-padding = { version = "0.3.0", features = ["no-entrypoint"] }
spl-tlv-account-resolution = { version = "0.10.0" }
test-case = "3.3"
